### ISSUE TITLE
Users have reported not being able to upload a token logo

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#2262]
## Steps to reproduce

This was run into when trying to add a token image to a create a colony with a new token process.

I have not been able to replicate this, however, Etienne has been able to. This was reported by a user and Etienne, who both have the following setup:
- Mac OSx
- Brave Version 1.65.114 Chromium: 124.0.6367.60 (Offizieller Build) (arm64)

## Expected behaviour

* All users should be able to upload a token logo when within the validation limitations.

## Actual behaviour

* Image uploads is giving a corrupted image error

![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/d0df0ea6-0cca-4576-9581-82edde9072e7)

**Comment by rdig** [comment]
We don't know what file the user was trying to upload. Just saying "logo" or "image" is not enough, as there are many formats and many more encoding, and especially random images will mascarade as something they're not.

To properly investigate this, we need the file the user was trying to upload

**Comment by arrenv** [comment]
> We don't know what file the user was trying to upload. Just saying "logo" or "image" is not enough, as there are many formats and many more encoding, and especially random images will mascarade as something they're not.
> 
> To properly investigate this, we need the file the user was trying to upload

Hey @rdig, sure thing, please see attached images provided by the user.

![Logo_klein](https://github.com/JoinColony/colonyCDapp/assets/33682027/185baf64-1080-45fe-9223-acc1e200adcd)
![Logo_klein](https://github.com/JoinColony/colonyCDapp/assets/33682027/129ae056-51c2-4dce-93c7-ed57fa26fc29)

**Comment by davecreaser** [comment]
Hey @rdig and whoever picks this up (possible even future me!) I also am getting this error, but in the user avatar uploader.

I'm trying with a 450x450 PNG of size 210KB.

Tried with lots of images which should be working too, but running into the same issue. Chrome on a mac.

**Comment by melyndav** [comment]
Commenting on this issue as I am still experiencing the issue corrupted issue from #2296 

As you can see, the image uploaded shows a corrupted error message but successfully shows in the user avatar in the user header and next to the upload form. 

<img width="1655" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/51aa93cb-1336-40d7-bd9f-09fa3da3f568">


Image used for testing: 
![github](https://github.com/JoinColony/colonyCDapp/assets/82127904/0ca8f144-af15-417b-bb17-e27b39bd639f)

**Comment by davecreaser** [comment]
Another note for the future solver of this ticket: please also ensure that the fourth issue here https://github.com/JoinColony/colonyCDapp/issues/2267 is also covered with this fix. It seems very much related!

**Comment by melyndav** [comment]
Another issue that needs to be addressed with this component fixing identified by @iamsamgibbs: When editing a colony, if you cancel the upload, it shows the blockie logo rather than the current colony logo as shown in the video below:

https://github.com/JoinColony/colonyCDapp/assets/82127904/aa1106c8-ba48-4360-a280-237a827c9532

The correct behavior for the 'Edit a Colony' and also for the avatar upload in the user account area should be that it retains the previous uploaded image. 

For the token upload during the Colony creation flow, it should default to a blockie since there will be no previous image file uploaded by the user.

**Comment by arrenv** [comment]
Getting upload issues in QA at the moment with the following error:

![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/97f0c8db-3c03-4e1f-a1e3-bf27fc34a831)

This is the image being used:

![profile](https://github.com/JoinColony/colonyCDapp/assets/33682027/88dbfc3e-237d-4014-ad92-2064a76defed)

**Comment by arrenv** [comment]
> That's not a upload error, it's an "optimization" issue. We have a method called `getOptimisedAvatarUnder300KB` which parses all images to try and compress them a bit.
> 
> It seems that with this particular image it has some issue.
> 
> Fix here is simple, but we'll first have to investigate what, if anything, removing this optimization breaks

Thanks for letting me know, I tested with about 5 images, including with jpgs, and also ones that have worked for me before.

**Comment by rumzledz** [comment]
Hey @arrenv thanks for finding out that the upload issue goes away when Brave shields are down. But after speaking to the guys, it seems that we don't officially support Brave as of the moment. Just wanted to check if the users who experience this issue are all on Brave and if that's the case, I wonder if we can de-prioritise this ticket?

**Comment by rumzledz** [comment]
Hi @arrenv, I've investigated this with @chmanie & @rdig. It turns out that the library responsible for processing the files does not function properly when Brave's fingerprint blocking feature is enabled, which is toggled on as part of enabling Brave Shield. They have a very explicit error message for this:

`"Pica: cannot use getImageData on canvas, make sure fingerprinting protection isn't enabled"`

The proper solution is likely going to take a huge effort compared to a temporary solution that we can readily use.

Here's a proposal for a message we can show to users when the app throws an error during file upload selection.

![Image](https://github.com/JoinColony/colonyCDapp/assets/50642296/49b553f3-0462-47f8-8c93-ac1155838789)
