### ISSUE TITLE
Staged payments no longer handling uninstalled extension

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#3304]
## Steps to reproduce

1. Ensure you have the Staged payment extension installed.
2. Create a new Staged payment.
3. Go through the entire process, up until the Payment step.
4. Uninstall the Staged payment extension.
5. Return to the action and try to make payments.
6. Note the error in the console (with MetaTx disabled).

## Expected behaviour

As added in this issue - https://github.com/JoinColony/colonyCDapp/pull/2719

* There should be a message to cancel the payment in the case where a Staged payment not yet finalizable has had the Staged payment extension uninstalled.
* There should be an error that is shown to users for Staged payments in the Payment step, where the extension has been uninstalled. 

![image](https://github.com/user-attachments/assets/bf78eb5e-3370-440f-b0ef-387861e52ae0)

![image](https://github.com/user-attachments/assets/98170fdb-8d93-41ae-b9dc-b01ff228fe1c)

## Actual behaviour

* You are able to continue with a Staged payment that is no longer a staged payment after the extension is uninstalled.
* You are given the option to make payments within staged payment that has had the extension uninstalled.

![image](https://github.com/user-attachments/assets/6ba58a7e-eea6-4b10-86d5-6b65eb58fe94)

**Comment by jakubcolony** [comment]
Resolved in #3279:

<img width="380" alt="image" src="https://github.com/user-attachments/assets/bf5214d9-6179-4330-91c7-ae6aab821a8c">
<img width="393" alt="image" src="https://github.com/user-attachments/assets/97826b42-ca6f-420e-aeee-7324f7f9d271">
<img width="391" alt="image" src="https://github.com/user-attachments/assets/5035e394-537c-44b2-9c35-0007a9844eb6">
<img width="383" alt="image" src="https://github.com/user-attachments/assets/7783ea39-868c-4835-859e-b6af47d53e0f">

**Comment by arrenv** [comment]
@jakubcolony I am still getting issues with Staged payment that are in the finalized state and the extension has been uninstalled, then a new extension has been installed.

![image](https://github.com/user-attachments/assets/fa99d17e-ff2a-4cb3-a0aa-ddf4276f728b)
