### ISSUE TITLE
Production: Activity feed pagination resets when sidepanel is triggered

### ISSUE THREAD

**Issue by melyndav** [JoinColony/colonyCDapp#3633]
## Steps to reproduce

1. Navigate to the activity feed
2. Using the pagination UI, go to any page that isn't the first page. Such as Page 2.
3. Select any transaction in the activity feed.
4. When the sidepanel opens, notice the activity feed resets to the first page, losing the page of the activity feed you were on. 

## Expected behaviour

When a sidepanel is triggered open, the activity feed on both the activity and dashboard pages (or any table where pagination is present) should not reset your position. 

## Actual behaviour

The pagination gets reset when a sidepanel is opened. This is a frustrating UX as users are forced to navigate back every time a new sidepanel is opened.

**Comment by rdig** [comment]
I remember this being fixed by @mmioana recently, or am I mistaken ?

**Comment by melyndav** [comment]
@rdig I found this issue while on a call with @iamsamgibbs today. He mentioned it wasn't fixed in that issue IIRC (hence why I raised this one ☺️)

**Comment by iamsamgibbs** [comment]
I believe @mmioana 's fix was on the recent activity table on the dashboard, I'm not sure if the same fix will have resolved this issue with the main activity feed.

**Comment by melyndav** [comment]
Hey @mmioana! Just looking at my open issues and prioritizing these. Any updates on this and it being resolved in the previous activity feed updates?

**Comment by melyndav** [comment]
Thanks @mmioana! ☺️
