### ISSUE TITLE
[Activity -QA] Date filter not displaying activities for all selected dates when custom and preset dates are selected simultaneously

### ISSUE THREAD

**Issue by olgapod** [JoinColony/colonyCDapp#3697]
## Steps to reproduce

1. Navigate to the Activity Feed.
2. Open the date filter and select a preset date option (e.g., "Past 24 hours").
3. Additionally, set a custom date range that spans a few days.
4. Observe the activities displayed within the selected date options.

## Expected behaviour

* The Activity Feed should display all activities that fall within both the preset and custom date ranges, providing a complete view of activities matching the selected filters.

## Actual behaviour

* When both custom and preset date ranges are selected, not all activities within those dates are displayed, leading to missing entries and inconsistent filter behavior.

<img width="1636" alt="image" src="https://github.com/user-attachments/assets/891cdfe6-33db-4382-8474-83da8191c455">

**Comment by arrenv** [comment]
This should have been already fixed in this issue - https://github.com/JoinColony/colonyCDapp/issues/2792

**Comment by davecreaser** [comment]
Discussed with @arrenv and we will just make the date options not multiple choice, so you can only choose one at a time. Working on that PR now!

**Comment by olgapod** [comment]
Hey @davecreaser! I can activate all checkboxes and select Custom date range. Do we still have an issue? 
<img width="1548" alt="image" src="https://github.com/user-attachments/assets/8eb2503c-7354-436e-b808-5de2d0717ab1" />
